languague: node_js
os: linux

cache: 
    directories:
        - node_modules
        - ~/.npm

node_js:
    - '12'

git: 
    depth: 3
script:
    - yarn build

deploy:
    provides: pages
    skip_cleanup: true
    keep_ history: true
    github_token: $GITHUB_TOKEN

    local_dir: dist/
    target_branch: gh-pages
    commit_messages: "Deploy de proyecto"
    on
        branch: master
